### ISSUE TITLE
how about installations?

### ISSUE THREAD

**Issue by anhphongbkdn** [canyie/Riru-IsolatedMagiskHider#1]
I have installed from magisk v20.4 module but it failed

**Comment by canyie** [comment]
What's the magisk manager shows?

**Comment by anhphongbkdn** [comment]
[magisk_install_log_2021-01-01T053742Z.log](https://github.com/canyie/Riru-IsolatedMagiskHider/files/5758985/magisk_install_log_2021-01-01T053742Z.log)

This is the log magisk manager

**Comment by anhphongbkdn** [comment]
- Copying zip to temp directory
- Installing Riru-IsolatedMagiskHider.zip
update-binary: line 2: 
: not found
update-binary: line 6: 
: not found
update-binary: umask: line 7: illegal mode: 022
update-binary: line 8: 
: not found
update-binary: line 161: syntax error: unexpected word (expecting "do")
! Installation failed

**Comment by canyie** [comment]
It seems that the line separator in the script file in your zip is CR LF, modify it to LF and try to install again

**Comment by canyie** [comment]
This issue will be closed because no response.
