### ISSUE TITLE
art参数异常，分区挂载异常

### ISSUE THREAD

**Issue by brijagstu7** [canyie/Riru-IsolatedMagiskHider#10]
![Screenshot_20210531-192206.png](https://user-images.githubusercontent.com/56994423/120186154-b29b8280-c245-11eb-9696-eaf8981e45d2.png)
请问可以解释一下这2个异常吗？不知道art参数异常是不是预示xposed框架的存在，而分区挂载异常预示着解开了启动加载锁和使用第三方ROM？有解决的可能性吗

**Comment by canyie** [comment]
ART 参数异常通常是 Xposed 类框架的特征，分区挂载异常应该是指只读分区被挂载为了可写。我不是 momo 开发者，能推测出来的大概就这些。

**Comment by uoox** [comment]
和我一模一样，不知道和存储空间隔离app有没有关系
