### ISSUE TITLE
Init.rc test failed

### ISSUE THREAD

**Issue by pippo73** [canyie/Riru-IsolatedMagiskHider#12]
Hi, 
I'm running on a miatoll phone running arrowos (andorid 11) and magisk 23.0 + Riru 26.1.1.r500 + Momohider 0.0.7.
I've created the empty files in /data/adb/modules/riru_momohider/config app_zygote_magic, initrc, isolated, magisk_tmp, setns
if I run magiskdetector 2.3, su file, system file, selinux tests are passet, but the initrc is detected as modified by magisk.

Do I miss something? or there is an issue?
Hope someone could help me

**Comment by canyie** [comment]
It's MagiskDetector's issue, the init.rc item may shows detected randomly even if magisk is not installed

**Comment by pippo73** [comment]
How strange. I'm trying this module since this app (https://play.google.com/store/apps/details?id=mc.gouv.mconnect) is detecting the "alterations" on my phone and I was looking for a solution.

When I've tested this module the only strange thing was the rc detections.

What else it could? Any hint?

**Comment by canyie** [comment]
Maybe this app detects other things like Magisk app. Anyway that's not what we should be dealing with.
