### ISSUE TITLE
Functions not working with Zygisk (Alpha Magisk)

### ISSUE THREAD

**Issue by pndwal** [canyie/Riru-IsolatedMagiskHider#13]
Latest cb4361b7-alpha Magisk (which merges recent TJW commits) is all good for my RN8T with both Riru and Zygisk. But setns/isolated and app_zygote_magic Riru-MomoHider configurations are incompatible w/ Zygisk and cause instability / system crashes / loss of root. 

initrc-only configuration is stable / ok however.

**Comment by canyie** [comment]
Riru modules are not compatible with Zygisk. Use Shamiko module if you want to use Zygisk.
