### ISSUE TITLE
Crave TV issues

### ISSUE THREAD

**Issue by Nolij** [canyie/Riru-IsolatedMagiskHider#15]
Crave TV can still detect root, and almost all setups I've tried also result in Momo showing "broken environment". I've tried variations of all following modules/toggles

Riru-MomoHider (tried variations of all 4 settings)
Riru-Unshare
HideMyApplist (LSposed, with Magisk module)
Magisk (newest pre-MagiskHide removal canary and latest canary with Zygisk)
Universal SafetyNet Fix (UNSF) (2.2 and 2.1 accordingly for the proper Magisk version, also tried with this off on both Magisk versions however for 2.2 MagiskHide functionally is lost entirely without this module so even if that did work SafetyNet wouldn't pass which would defeat the purpose)
Sui
MagiskHide (as for UNSF even if disabling this could fix Momo I'd still fail SafetyNet without it so unless there's another fix for that won't be turning it off)

I do not have any overlay modules installed to the best of my knowledge

My main intention is to get Crave TV working however I'd also like to pass Momo, it has not for any config not stated "Device is rooted" when I try to watch a movie or TV show on it

MagiskDetector passes all tests but init.rc at the moment (it fails that consistently, only passed it for 1 config that I can't reproduce. I'm fairly sure it was on latest Magisk)

Device Info:
OnePlus 7 Pro 12GB (GM1917)
Latest Vendor
crDroid 7.11 Official (Android 11)

Please let me know if I've left anything out

**Comment by canyie** [comment]
If MagiskDetector passes all tests then this module is working properly. The failure of init.rc test is MagiskDetector's problem. Maybe the app detects other things, but that's not what we should be dealing with.
