### ISSUE TITLE
环境异常 检测到对环境的修改

### ISSUE THREAD

**Issue by shamrock33** [canyie/Riru-IsolatedMagiskHider#17]
![is1](https://user-images.githubusercontent.com/38095859/151122242-0b23e10f-37d8-4db4-b6ef-2d6e86c01d15.jpg)
![is2](https://user-images.githubusercontent.com/38095859/151122265-9f7fe8e7-8d79-4261-a49c-6da11ddfdcea.png)

**Comment by canyie** [comment]
没有设备信息，没有系统版本，没有日志，也没提供 magisk hide 有没有开，无效反馈。
