### ISSUE TITLE
Documentation for Shamiko?

### ISSUE THREAD

**Issue by ghost** [canyie/Riru-IsolatedMagiskHider#18]
I have created config for it but it seems to not take any effect after reboot. Is there a documentation for Shamiko or it's pretty much same as Riru-MomoHider?

**Comment by canyie** [comment]
> ### Usage
> 1. Install Shamiko and enable Zygisk and reboot
> 1. Turn on denylist to configure denylist.
> 1. Once denylist is configured, disable it to activate Shamiko

Read the README.md in Shamiko module zip.

**Comment by fanterihackk** [comment]
> I have created config for it but it seems to not take any effect after reboot. Is there a documentation for Shamiko or it's pretty much same as Riru-MomoHider?

I did it too, it worked for me, if you want to reach me, write me on Telegram, my telegram name is @FanteriBey

**Comment by canyie** [comment]
@fanterihackk Now, this cheat expert got banned from my telegram group.
