### ISSUE TITLE
Momo shows "environment is broken, service not responding"

### ISSUE THREAD

**Issue by maahmoudsamir** [canyie/Riru-IsolatedMagiskHider#19]
Hi bro i need a solution for this problem 
Momo shows "environment is broken, service not responding"
Device : note 8 pro ( begonia ) - android 11
Miui china beta mod 21.11.10 
Magisk : 24.1 stable
Zygisk : yes 
Shamiko : flashed
Everything is ok and i can't know the problem

![Screenshot_2022-02-21-03-35-59-783_io github vvb2060 mahoshojo](https://user-images.githubusercontent.com/57969899/154891901-06a8b8de-b82b-4758-8d82-b3bff0640b64.jpg)

**Comment by HuskyDG** [comment]
Your issue is invalid

**Comment by canyie** [comment]
no log, no fix.

**Comment by maahmoudsamir** [comment]
> 

There is a bank app that isn't working bro

**Comment by HuskyDG** [comment]
> > 
> 
> There is a bank app that isn't working bro

You don't provide any information (log, etc) that owner need.
So anything you say is useless.

**Comment by maahmoudsamir** [comment]
How to catch log bro 
This is all info i get it
Which info does he need ?

**Comment by HuskyDG** [comment]
> How to catch log bro This is all info i get it Which info does he need ?

Stop abuse "bro" word. Everyone are not Your friend

**Comment by maahmoudsamir** [comment]
> > How to catch log bro This is all info i get it Which info does he need ?
> 
> Stop abuse "bro" word. Everyone are not Your friends

Don't leave the point and talk about useless things

**Comment by HuskyDG** [comment]
> > > How to catch log bro This is all info i get it Which info does he need ?
> > 
> > 
> > Stop abuse "bro" word. Everyone are not Your friends
> 
> Don't leave the point and talk about useless things

Your issue is not related to Momohider, how should i not live the point

**Comment by maahmoudsamir** [comment]
I mean there is a problem with the system that momo app detected so I think the app isn't working bcz of that

**Comment by HuskyDG** [comment]
> > > How to catch log bro This is all info i get it Which info does he need ?
> > 
> > 
> > Stop abuse "bro" word. Everyone are not Your friends
> 
> Don't leave the point and talk about useless things

Try turning off all your modules exclude Shamiko

**Comment by maahmoudsamir** [comment]
> Try turning off all your modules exclude Shamiko and make sure it is caused by Shamiko

Ok i will try and check again

**Comment by canyie** [comment]
> Don't leave the point and talk about useless things

Issue locked until you know how to follow rules.
