### ISSUE TITLE
Magisk24.1 MOMO 🤧

### ISSUE THREAD

**Issue by aamirwaseem439** [canyie/Riru-IsolatedMagiskHider#20]
I have issue in MOMO it shows checksum and boatloader unlocked while, zygisk is enable denylist is done,
Shamiko installed yet facing this issue in magisk 24.1![Screenshot_2022-02-23-16-50-13-216_io.github.vvb2060.mahoshojo.jpg](https://user-images.githubusercontent.com/81899483/155314334-6075095a-35bd-4e44-94cf-93f2b067ddf3.jpg)

**Comment by HuskyDG** [comment]
If you are not stupid, you will not ask that.
Moreover, your issue is INVALID

**Comment by aamirwaseem439** [comment]
I have got NO KNOWLEDGE of it, that is why i am asking 🙂

**Comment by HuskyDG** [comment]
> I have got NO KNOWLEDGE of it, that is why i am asking 🙂

It can't be hidden because of hardware attestation. I also have that problem. You should ignore it

**Comment by aamirwaseem439** [comment]
> > I have got NO KNOWLEDGE of it, that is why i am asking 🙂
> 
> It can't be hidden because of hardware attestation. I also have that problem. You should ignore it

Okay, Thanks for your precious time 🙂

**Comment by HuskyDG** [comment]
> > > I have got NO KNOWLEDGE of it, that is why i am asking 🙂
> > 
> > 
> > It can't be hidden because of hardware attestation. I also have that problem. You should ignore it
> 
> Okay, Thanks for your precious time 🙂

So close the issue
