### ISSUE TITLE
Need some guidance 

### ISSUE THREAD

**Issue by Abdullah3119** [canyie/Riru-IsolatedMagiskHider#21]
Firstly your module really highly appreciated.
I have read troubleshoot and i know following detections are not related to this module

SElinux rules are modified
Partition mounted abnormally
Art parameters are abnormal

But as these problems are detected by momo can you please send me some relavent to stuff to study and fix these problems .
Thankyou

Device : Samsung A70
Rom : Offical
Magisk version : 24.1 stable (zygisk enabled)
Android version : 10
Modules : lsposed, shamiko, safetynet
SElinux : enforce

**Comment by HuskyDG** [comment]
Uninstall momo and magisk, reflash stock rom and lock bootloader
