### ISSUE TITLE
[Only in Momo 4.4.1] Found Zygisk

### ISSUE THREAD

**Issue by j0110** [canyie/Riru-IsolatedMagiskHider#24]
Hi,
I updated Momo to v4.4.1 and get the "Found Zygisk" warning, but it wasn't detected in previous versions.
What has changed, and how to hide zygisk ?
Thanks for your help
![Screenshot_20220824-150542_Momo](https://user-images.githubusercontent.com/23175256/186414394-c14347fd-b9ae-454f-b0ac-2ae04f3c9a15.png)

**Comment by mizuhashikuniumi** [comment]
@j0110 Proo

**Comment by canyie** [comment]
Sorry, but I don't know. 
And if your apps do not detect root, why torture yourself with momo?

**Comment by j0110** [comment]
Just to finish perfectly the hard work.

And do you know how to get rid of the "device is running a custom ROM" warning ?
