### ISSUE TITLE
[Question] How to bypass detect magisk in isolated.

### ISSUE THREAD

**Issue by loveedxposed** [canyie/Riru-IsolatedMagiskHider#4]
https://darvincitech.wordpress.com/2019/11/04/detecting-magisk-hide/
this app still detect, pls help me.

**Comment by canyie** [comment]
I tested this app and it showed me "Magisk Not Found".
I need more info (e.g. Android version) to solve this problem.

**Comment by canyie** [comment]
Any more info?

**Comment by canyie** [comment]
No reply, close.
