### ISSUE TITLE
Hide "Magisk su processes"

### ISSUE THREAD

**Issue by Mark-Joy** [canyie/Riru-IsolatedMagiskHider#6]
Hiiii,
Great app so far. The last thing It can't hide from "magisk detector" is "magisk su processes". Is there a way to hide it now?

![IMG_20210415_050140](https://user-images.githubusercontent.com/22109528/114787870-a7ca8280-9daa-11eb-818c-b1ed806afea0.jpg)

**Comment by jh0bc** [comment]
I think you should share more details about your device, android version, magisk version, modules installed ... etc

Btw do you enabled Magisk Hide for the "Magisk Detector" app?

**Comment by Mark-Joy** [comment]
Redmi Note 8 Pro
Android 9
Rom xiaomi.eu 11.0.2.0

Magisk 22.1
Riru 25.4.1
Momohider 0.0.4
Magisk detector 2.3

Magisk hide is enable.

![Screenshot_2021-04-16-13-28-22-385_com topjohnwu magisk](https://user-images.githubusercontent.com/22109528/114981957-f8c89c80-9eb8-11eb-98d7-161353928513.jpg)
![Screenshot_2021-04-16-13-32-31-383_com topjohnwu magisk](https://user-images.githubusercontent.com/22109528/114981983-05e58b80-9eb9-11eb-9e18-19f788b22c3e.jpg)

Also, init.rc was hidden after first phone reboot. But close then re-open "magisk detector" show init.rc was modified.
![Screenshot_2021-04-15-18-16-38-347_io github vvb2060 magiskdetector](https://user-images.githubusercontent.com/22109528/114982312-78ef0200-9eb9-11eb-9e2e-3dc684ce0e2d.jpg)

![IMG_20210416_134607](https://user-images.githubusercontent.com/22109528/114982930-3aa61280-9eba-11eb-908e-cb16c3516647.jpg)

"Detect Magisk" app by Darvin is hidden successfully.

![Screenshot_2021-04-16-13-46-18-551_com darvin security](https://user-images.githubusercontent.com/22109528/114983165-76d97300-9eba-11eb-8c39-d1b1e9df7385.jpg)

**Comment by canyie** [comment]
Try upgrade to Android 10, and make sure your SELinux policy is correct

**Comment by Mark-Joy** [comment]
Hi, today I updated all modules to the latest version except my Android version. Due to various reasons, my custom ROM doesn't have android 10 version. xiaomi.eu team (custom ROM team) dropped their support for this device because the device is easily hard bricked if not handle carefully during update and root processes. Hence, I rather not messing with it at the moment.

The issue with init.rc seems to be resolved. Only the "magisk su processes" is left.
![Screenshot_2021-05-28-07-20-44-002_rikka riru](https://user-images.githubusercontent.com/22109528/119913481-39233c00-bf88-11eb-8f44-e719ea5af8fc.jpg)
![Screenshot_2021-05-28-07-21-02-706_io github vvb2060 magiskdetector](https://user-images.githubusercontent.com/22109528/119913483-3aecff80-bf88-11eb-8d88-6d20ff4e6459.jpg)



Redmi Note 8 Pro
Android 9
Rom xiaomi.eu 11.0.2.0

Magisk 23.0
Riru 25.4.4
Momohider 0.0.7
Magisk detector 2.3

Magisk hide is enable.

**Comment by Didilinggarjati** [comment]
Cara mengatasi unit rc gimana..?

**Comment by Didilinggarjati** [comment]
![Uploading 119913483-3aecff80-bf88-11eb-8d88-6d20ff4e6459.jpg…]()
