### ISSUE TITLE
magisk hide仍然能被Momo检测到

### ISSUE THREAD

**Issue by lololowe** [canyie/Riru-IsolatedMagiskHider#8]
Redmi 10X 4G
Android 11
Rom MIUI 
![Screenshot_2021-05-10-10-33-06-382_io github vvb2060 mahoshojo](https://user-images.githubusercontent.com/72289066/117599358-41a00800-b17c-11eb-81ab-bf1e0c3473b6.jpg)
12.0.5

Magisk 22.1
Riru 25.4.4
Momohider 0.0.7
Momo 3.1.1
已对目标应用开启magiskhide

**Comment by canyie** [comment]
app_zygote_magic开没开
