### ISSUE TITLE
magisk-lite新版momohider0.0.7刷入失败

### ISSUE THREAD

**Issue by Haokun-hkun** [canyie/Riru-IsolatedMagiskHider#9]
![Screenshot_2021-05-28-18-33-40-915_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/80605952/119971565-bfcf1d80-bf76-11eb-885a-628d52b82118.jpg)
![Screenshot_2021-05-28-18-27-18-313_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/80605952/119971588-c65d9500-bf76-11eb-9410-d4fe2129e6e8.jpg)

**Comment by canyie** [comment]
很有可能是你下载的 zip 损坏了，或者你的 magisk 问题。
